#!/bin/bash
#
# fpd2pdf - Print a set of Fped files into a PDF
#
# Written 2010-2011 by Werner Almesberger
# Copyright 2010-2011 Werner Almesberger
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#


usage()
{
    cat <<EOF 1>&2
usage: $0 [-a] [-o out.pdf] [-P] file.fpd[:package] ...

  -a          also include files whose name contains a tilde (backup files)
  -o out.pdf  write to the specified file (default: standard output)
  -P          use full page drawings
EOF
    exit 1
}


out=-
all=false
p_opt=-p

while true; do
    case "$1" in
    -a)	all=true
	shift;;
    -o)	[ -z "$2" ] && usage
	out="$2"
	shift 2;;
    -P)	p_opt=-P
	shift;;
    -*)	usage;;
    *)	break;;
    esac
done

[ -z "$1" ] && usage

eval gs -q -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile=$out -f \
  `for n in "$@"; do $all || [ "$n" = "${n/\~/}" ] && \
  echo "<(fped $p_opt  \
    \"\`echo \\"$n\\" | sed 's/:.*//'\`\" \
    \`echo \"$n\" | sed 's/.*:/-1/p;d'\` \
    -)"; done`
